version: '3.1'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: flux
      POSTGRES_PASSWORD: flux
    ports:
      - "5434:5432"
    volumes:
      - webflux_data:/var/lib/postgres/data

volumes:
  webflux_data: